name: Syncronize fork with original

on:
  schedule:
    - cron: "*/10 * * * *"

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: apt install git-all -y
      
      - name: Update branch main
        run: |
          git remote add upstream https://github.com/felipemoskado/sync-fork.git
          git fetch upstream
          git checkout main
          git merge upstream/main
          git push origin master